FROM docker.io/alpine:latest AS copy_repo

COPY add-rpm-fusion.sh /add-rpm-fusion.sh
RUN chmod +x /add-rpm-fusion.sh

FROM registry.fedoraproject.org/fedora-toolbox:latest

RUN --mount=type=bind,from=copy_repo,source=/,target=/ctx \
    /ctx/add-rpm-fusion.sh


RUN dnf install -y \
	neovim \
	fish \
	wlroots \
	xsel \
	git \
	curl \
	wget \
	tmux \
	wl-clipboard \
	python3-pip

RUN mkdir /usr/share/container-setup

COPY setup /usr/share/container-setup/

RUN chmod +x /usr/share/container-setup/init.sh
RUN	chmod +x /usr/share/container-setup/install-brew.sh 
RUN	chmod +x /usr/share/container-setup/chmod-setup.sh

# Make all init-scripts executable
RUN /usr/share/container-setup/chmod-setup.sh