FROM registry.fedoraproject.org/fedora-toolbox:latest

RUN type=tmpfs,dst=/ chmod +x /add-rpm-fusion.sh && /add-rpm-fusion.sh

RUN dnf install -y \
	neovim \
	fish \
	wlroots \
	xsel \
	git \
	curl \
	wget \
	tmux \
	wl-clipboard

RUN mkdir /usr/share/container-setup

COPY setup /usr/share/container-setup/

RUN chmod +x /usr/share/container-setup/init.sh
RUN	chmod +x /usr/share/container-setup/install-brew.sh 
RUN	chmod +x /usr/share/container-setup/chmod-setup.sh

# Make all init-scripts executable
RUN /usr/share/container-setup/chmod-setup.sh