FROM docker.io/alpine:latest

COPY add-adoptium.sh /add-adoptium.sh
RUN chmod +x /add-adoptium.sh

FROM ghcr.io/vincentvibe3/fedora-toolbox-commons:latest

RUN --mount=type=bind,from=copy_repo,source=/,target=/ctx \
    /ctx/add-adoptium.sh

# Install java in the same step
# needs the && because the repo needs to be installed first
RUN dnf install -y \
    go \
    clang \
    rustup \
    gcc \
    nodejs \
    libatomic 


RUN sudo dnf install -y \
    termurin-21-jdk \
    termurin-25-jdk 


COPY setup /usr/share/container-setup/

# Make all init-scripts executable
RUN /usr/share/container-setup/chmod-setup.sh