FROM ghcr.io/vincentvibe3/ubuntu-toolbox-commons:latest

RUN apt-get update && apt-get install -y \
	libfuse2 \
	libnss3 \
	libnspr4 \
	libasound2t64 \
	libxcb-keysyms1 \
	libxcb-image0 \
	libxkbcommon-x11-0 \
	libxcb-util1 \
	libxcb-xkb1 \
	libglib2.0-bin \
	libglib2.0-0t64

COPY setup /usr/share/container-setup/

# Make all init-scripts executable
RUN /usr/share/container-setup/chmod-setup.sh