name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  common:
    name: Build common base Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: ./fedora-commons
        push: true
        file: ./fedora-commons/Containerfile
        tags: |
          ghcr.io/vincentvibe3/fedora-toolbox-commons:latest, ghcr.io/vincentvibe3/fedora-toolbox-commons:${{github.sha}}
  
  build:
    name: Build images
    needs: common
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        containers:
          # !! Add your recipes here
          - development
          - matlab
          - latex
          - tools
          
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./${{matrix.containers}}
          push: true
          file: ./${{matrix.containers}}/Containerfile
          tags: |
            ghcr.io/vincentvibe3/toolbox-${{ matrix.containers }}:latest, ghcr.io/vincentvibe3/toolbox-${{ matrix.containers }}:${{github.sha}}